version: '3'

# Automated test compose file.

services:
  app:
    image: lochnerr/chronyd
    restart: "no"
    hostname: app.example.com
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
      - setgid
      - setuid
      - sys_time
      - dac_override
    volumes:
      - chrony:/srv/chrony
    networks:
      testnet:
        ipv4_address: 10.30.50.2
  sut:
    image: lochnerr/chronyd
    command: /usr/local/bin/run-sut.sh
    restart: "no"
    hostname: sut.example.com
    cap_drop:
      - ALL
    cap_add:
      - net_bind_service
      - setgid
      - setuid
      - sys_time
    volumes:
      - chrony:/srv/chrony
    networks:
      testnet:
        ipv4_address: 10.30.50.3
    depends_on:
      - app

volumes:
  chrony:

networks:
  testnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24

